// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CacheStatus = { root: string, total_bytes: number, free_bytes: number | null, entries: Array<DatasetEntry>, };

export type DatasetEntry = { collection: string, item: string, file: string, bytes: number, inflated: boolean, fetched_at: string | null, };

export type ReleaseInfo = { collection: string, item: string, datetime: string | null, asset: string, href: string, 
/**
 * Wire size of the archive, when the server reports it.
 */
archive_bytes: number | null, 
/**
 * Inflated size of the member inside the archive.
 */
member_bytes: number | null, member_name: string | null, cached: boolean, };

export type TaskDone = { task_id: string, path: string, };

export type TaskError = { task_id: string, message: string, };

export type TaskProgress = { task_id: string, read: number, total: number | null, written: number, retries: number, };
