// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable administrative unit (SPEC.md FR-33).
 */
export type AdminUnitInfo = { 
/**
 * `kantonsnummer`, `bezirksnummer` or `bfs_nummer` — stable, unlike the name.
 *
 * Typed as `number`, not `bigint`: ts-rs maps i64 to bigint, but these arrive as
 * ordinary JSON numbers and no unit number comes close to 2^53.
 */
number: number, name: string, 
/**
 * Canton, shown because commune names are not unique.
 */
canton: string, population: number, areaKm2: number, };

export type AreaInfo = { areaKm2: number, 
/**
 * [west, south, east, north] in WGS84, for the map view.
 */
wgs84: [number, number, number, number], withinSwitzerland: boolean, 
/**
 * Predicted output size from the calibrated model (FR-60).
 */
estimatedBytes: number, 
/**
 * The device budget the estimate is measured against, and the hard ceiling
 * above it. Shown together with the estimate (FR-63).
 */
budgetBytes: number, hardLimitBytes: number, overBudget: boolean, 
/**
 * True once the model has been refit from the user's own builds.
 */
calibrated: boolean, 
/**
 * How many real builds the model has seen.
 */
modelSamples: number, 
/**
 * False when swissTLM3D is absent, so feature counts could not be read and the
 * estimate is area-only. The UI says so rather than implying precision.
 */
countedFeatures: boolean, };

/**
 * Geometry facts plus a calibrated size estimate for a candidate area.
 *
 * The content parameters are optional so the area step can ask before content has
 * been chosen; they default to the hiking preset's settings, which is what the
 * wizard starts with.
 * The area and content parameters an estimate depends on, as one value: a command
 * with eight positional arguments is easy to call wrongly from the frontend.
 */
export type AreaQuery = { minE: number, minN: number, maxE: number, maxN: number, deviceId: string, 
/**
 * Absent until the content step has been visited.
 */
preset: string | null, contourM: number | null, relief: string | null, };

export type BuildFinished = { taskId: string, gmapsupp: string, bytes: number, tileCount: number, features: number, contourLines: number, hasDem: boolean, warnings: Array<string>, 
/**
 * How long the build actually took. Shown on completion, and what makes the next
 * build's estimate credible.
 */
seconds: number, };

export type BuildProgress = { taskId: string, stage: string, stageLabel: string, stageIndex: number, stageCount: number, 
/**
 * Progress within the current stage, when the stage can report it.
 */
fraction: number | null, detail: string, 
/**
 * Progress through the whole build, weighted by how long each stage usually takes.
 */
overall: number, elapsedSeconds: number, 
/**
 * Seconds remaining, absent until the extrapolation would mean something (FR-71).
 */
etaSeconds: number | null, };

export type CacheStatus = { root: string, totalBytes: number, freeBytes: number | null, entries: Array<DatasetEntry>, };

export type ConnectedDevice = { mount: string, model: string | null, 
/**
 * Profile chosen for this device, if one matched.
 */
profileId: string | null, freeBytes: number | null, existingMaps: Array<string>, };

/**
 * Where data lives, how much room is there, and how much is already used.
 */
export type DataLocation = { path: string, 
/**
 * True when `S2G_CACHE` is set, in which case the setting is overridden and the
 * UI must say so rather than appearing not to work.
 */
fromEnvironment: boolean, 
/**
 * True when nothing is configured and the platform default is in use.
 */
isDefault: boolean, freeBytes: number | null, usedBytes: number, 
/**
 * Where that space went. The elevation tile cache is the part that grows without
 * bound, and it used to be invisible here.
 */
datasetBytes: number, elevationBytes: number, buildBytes: number, otherBytes: number, exists: boolean, };

export type DatasetEntry = { collection: string, item: string, file: string, bytes: number, inflated: boolean, fetchedAt: string | null, };

export type DeviceSummary = { id: string, displayName: string, family: string, screenClass: string, 
/**
 * vendor | measured | community | assumed
 */
confidence: string, confidenceVerified: boolean, confidenceNotes: string, budgetBytes: number, maxImgBytes: number, maxTiles: number, supportsDem: boolean, 
/**
 * True when this profile was matched to a connected device.
 */
connected: boolean, };

export type InstallPlan = { source: string, target: string, 
/**
 * True when a file would be replaced.
 */
overwrites: boolean, bytes: number, freeBytes: number | null, fits: boolean, };

export type LayerInfo = { 
/**
 * The source layer name, which is also what `Recipe.excludedLayers` holds.
 */
id: string, group: string, 
/**
 * How many attributes travel into the map with this layer, as a rough weight.
 */
attributeCount: number, 
/**
 * Which presets extract this layer at all.
 */
presets: Array<string>, };

export type PlaceMatch = { name: string, alternatives: Array<string>, populationCategory: string | null, easting: number, northing: number, lat: number, lon: number, };

export type PresetInfo = { id: string, needsWinter: boolean, needsCycle: boolean, contourM: number, indexContourM: number, 
/**
 * True when every dataset this preset needs is already downloaded.
 */
dataReady: boolean, 
/**
 * What is missing, for the disabled-with-a-reason UI (FR-51).
 */
missing: Array<string>, };

export type ReleaseInfo = { collection: string, item: string, datetime: string | null, asset: string, href: string, 
/**
 * Wire size of the archive, when the server reports it.
 */
archiveBytes: number | null, 
/**
 * Inflated size of the member inside the archive.
 */
memberBytes: number | null, memberName: string | null, cached: boolean, };

/**
 * One entry in the saved-recipe library (SPEC.md FR-55).
 */
export type SavedRecipeInfo = { id: string, name: string, deviceId: string, preset: string, areaLabel: string, areaKm2: number, savedAt: bigint, };

export type TaskDone = { taskId: string, path: string, };

export type TaskError = { taskId: string, message: string, };

export type TaskProgress = { taskId: string, read: number, total: number | null, written: number, retries: number, };

/**
 * An imported GPX or FIT track, ready to become a corridor (SPEC.md FR-38..FR-40).
 */
export type TrackImport = { name: string, 
/**
 * LV95 `[easting, northing]` pairs, simplified.
 */
points: Array<[number, number]>, lengthKm: number, ascentM: number, 
/**
 * Points before simplification, so the UI can say what was dropped.
 */
originalPoints: number, 
/**
 * False when part of the track falls outside the swisstopo coverage area.
 */
fullyWithinSwitzerland: boolean, };
