"""Generate docs/boundaries-schema.md from the real swissBOUNDARIES3D file.

Working agreement rule 2: every layer, attribute and value used in code must appear in a
document generated from the actual data. This is that generator for the administrative
boundaries (SPEC.md FR-33, FR-34).

    python3 tools/boundaries_schema.py

Acquire the dataset first if it is not cached:

    cargo run --release -p s2g-core --example acquire -- ch.swisstopo.swissboundaries3d
"""
from __future__ import annotations

import os
import sqlite3
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
COLLECTION = "ch.swisstopo.swissboundaries3d"


def cache_root() -> Path:
    if env := os.environ.get("S2G_CACHE"):
        return Path(env)
    settings = Path.home() / ".config" / "swisstopo2garmin" / "settings.json"
    if settings.is_file():
        import json
        root = json.loads(settings.read_text()).get("dataRoot")
        if root:
            return Path(root)
    return Path.home() / ".cache" / "swisstopo2garmin"


def find_gpkg() -> tuple[Path, str]:
    root = cache_root() / COLLECTION
    for item in sorted(root.glob("*"), reverse=True):
        for f in sorted(item.glob("*.gpkg")):
            return f, item.name
    sys.exit(
        f"no swissBOUNDARIES3D GeoPackage under {root}\n"
        f"acquire it with: cargo run --release -p s2g-core --example acquire -- {COLLECTION}"
    )


MEANING = {
    "tlm_landesgebiet": "countries: Switzerland, Liechtenstein, and the German and "
                        "Italian slivers the dataset covers",
    "tlm_kantonsgebiet": "the 26 cantons",
    "tlm_bezirksgebiet": "districts (Bezirke); not every canton has them",
    "tlm_hoheitsgebiet": "communes, plus unassigned cantonal territory and two Kommunanzen",
    "tlm_hoheitsgrenze": "boundary lines; the polygons above are what an area selection needs",
}

OBJEKTART_NOTES = {
    "Gemeindegebiet": "a commune — the only value an administrative-unit selection should offer",
    "Kantonsgebiet": "cantonal territory belonging to no commune, in practice lake surface",
    "Kommunanz": "shared territory belonging to several communes",
}

INTERESTING = {
    "id", "objektart", "name", "icc", "einwohnerzahl", "kantonsnummer",
    "bezirksnummer", "bfs_nummer", "shn", "hist_nr",
    "kantonsflaeche", "bezirksflaeche", "gem_flaeche", "landesflaeche", "see_flaeche",
}


def main() -> None:
    gpkg, item = find_gpkg()
    db = sqlite3.connect(gpkg)
    out: list[str] = []
    p = out.append

    p("# swissBOUNDARIES3D schema — read from the file, not the documentation")
    p("")
    p("Generated by `tools/boundaries_schema.py` from the real GeoPackage. Every layer,")
    p("attribute and value used in code must appear here (working agreement rule 2).")
    p("")
    p(f"- Source: `{COLLECTION}`, item `{item}`")
    p(f"- File: `{gpkg.name}` ({gpkg.stat().st_size:,} B)")
    p("- CRS: LV95 / EPSG:2056, heights LN02")
    p("")

    p("## Spatial layers")
    p("")
    p("| Layer | Geometry | Rows | What it is |")
    p("|---|---|---:|---|")
    layers = sorted(db.execute(
        "SELECT table_name, column_name, geometry_type_name FROM gpkg_geometry_columns"))
    for name, _gcol, gtype in layers:
        n = db.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        p(f"| `{name}` | {gtype} | {n:,} | {MEANING.get(name, '')} |")
    p("")

    p("## Attributes used by this project")
    p("")
    p("Every layer also carries `uuid`, `datum_aenderung`, `datum_erstellung`,")
    p("`erstellung_jahr/monat`, `grund_aenderung`, `herkunft`, `herkunft_jahr/monat`,")
    p("`revision_jahr/monat`, `revision_qualitaet` — provenance, not map content.")
    p("")
    for t in ("tlm_landesgebiet", "tlm_kantonsgebiet", "tlm_bezirksgebiet", "tlm_hoheitsgebiet"):
        info = list(db.execute(f'PRAGMA table_info("{t}")'))
        types = {r[1]: r[2] for r in info}
        p(f"### `{t}`")
        p("")
        p("| Attribute | Type | Distinct | Example |")
        p("|---|---|---:|---|")
        for c in [r[1] for r in info if r[1] in INTERESTING]:
            d = db.execute(f'SELECT COUNT(DISTINCT "{c}") FROM "{t}"').fetchone()[0]
            row = db.execute(
                f'SELECT "{c}" FROM "{t}" WHERE "{c}" IS NOT NULL LIMIT 1').fetchone()
            p(f"| `{c}` | {types[c]} | {d:,} | `{row[0] if row else ''}` |")
        p("")

    p("## Value domains that matter")
    p("")
    p("### `tlm_hoheitsgebiet.objektart`")
    p("")
    p("| Value | Rows | Meaning |")
    p("|---|---:|---|")
    for v, n in db.execute(
            "SELECT objektart, COUNT(*) FROM tlm_hoheitsgebiet "
            "GROUP BY objektart ORDER BY 2 DESC"):
        p(f"| `{v}` | {n:,} | {OBJEKTART_NOTES.get(v, '')} |")
    p("")
    p("### `icc` — which country a unit belongs to")
    p("")
    p("| Value | Communes | Cantons |")
    p("|---|---:|---:|")
    for (code,) in db.execute("SELECT DISTINCT icc FROM tlm_hoheitsgebiet ORDER BY icc"):
        g = db.execute(
            "SELECT COUNT(*) FROM tlm_hoheitsgebiet WHERE icc = ?", (code,)).fetchone()[0]
        k = db.execute(
            "SELECT COUNT(*) FROM tlm_kantonsgebiet WHERE icc = ?", (code,)).fetchone()[0]
        p(f"| `{code}` | {g:,} | {k:,} |")
    p("")
    p("The dataset extends past the border, so a selection must filter on `icc`.")
    p("")

    p("## Facts that shape the code")
    p("")
    dupes = list(db.execute(
        "SELECT name, COUNT(*) c FROM tlm_hoheitsgebiet GROUP BY name HAVING c > 1 "
        "ORDER BY c DESC"))
    listed = ", ".join(f"`{n}` ×{c}" for n, c in dupes[:4]) or "none in this release"
    p(f"1. **Commune names are not unique**: {len(dupes)} appear more than once "
      f"({listed}). A picker must show the canton alongside the name, exactly as the "
      "place search does.")
    p("2. **Geometry is MULTIPOLYGON throughout.** A commune can be several disjoint "
      "pieces (an exclave, or a lake share), so a mask has to be a union of polygons, "
      "not one ring.")
    p("3. **`bfs_nummer` is the stable identifier for a commune**, `kantonsnummer` for "
      "a canton, `bezirksnummer` for a district. Names change; numbers are what a saved "
      "recipe should store.")
    lakes = db.execute(
        "SELECT COUNT(*) FROM tlm_hoheitsgebiet WHERE objektart = 'Kantonsgebiet'"
    ).fetchone()[0]
    p(f"4. **{lakes} rows are lake surface, not communes** "
      "(`objektart = 'Kantonsgebiet'`). Offering them in a commune picker would be wrong.")
    p("5. **`einwohnerzahl` is present for every level**, so a picker can rank by "
      "population the way the place search does.")
    p("")
    p("---")
    p("")
    p("Regenerate:")
    p("")
    p("```")
    p("python3 tools/boundaries_schema.py")
    p("```")

    dest = REPO / "docs" / "boundaries-schema.md"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest} from {gpkg}")


if __name__ == "__main__":
    main()
