"""Derive the wrist-device style variant from the main style (SPEC.md FR-CART6).

A fenix screen is about 1.3 inch with far less rendering headroom than an Edge 1050.
The same style at the same density is both unreadable and slow, so the wrist variant:

  * raises every rule's minimum resolution, so detail appears only when zoomed in
  * drops the layers that contribute density without navigational value at wrist size
  * uses a coarser contour interval by raising the contour resolutions further

Derived rather than hand-maintained so the two variants cannot drift apart.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "style" / "swisstopo"
DST = REPO / "style" / "swisstopo-wrist"

# Rules whose types are simply too dense to be useful on a watch.
DROP_TYPES = {
    "0x10211",  # buildings: thousands of tiny polygons
    "0x1020d",  # parking / transport areas
    "0x1020b",  # orchards, nurseries
}
# Layers dropped wholesale.
DROP_LAYERS = {"tlm_namen_flurname", "tlm_eo_einzelobjekt", "tlm_areale_verkehrsareal"}

# Resolution bump per element kind. Higher resolution = appears only when zoomed in.
BUMP = {"lines": 1, "polygons": 1, "points": 2}
# Contours are the densest thing on an alpine map; push them back further.
CONTOUR_BUMP = 2
MAX_RESOLUTION = 24


def transform(text: str, kind: str) -> str:
    out = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            out.append(line)
            continue

        if any(layer in line for layer in DROP_LAYERS):
            out.append(f"# [wrist] dropped: too dense at wrist size\n#{line}")
            continue
        if any(t in line for t in DROP_TYPES):
            out.append(f"# [wrist] dropped: too dense at wrist size\n#{line}")
            continue

        bump = CONTOUR_BUMP if "contour" in line else BUMP.get(kind, 1)

        def raise_res(m: re.Match) -> str:
            return f"resolution {min(int(m.group(1)) + bump, MAX_RESOLUTION)}"

        out.append(re.sub(r"resolution (\d+)", raise_res, line))
    return "\n".join(out) + "\n"


def main() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    (DST / "version").write_text("1\n")

    for name in ("lines", "polygons", "points", "relations"):
        src = SRC / name
        if not src.exists():
            continue
        (DST / name).write_text(
            f"# GENERATED from style/swisstopo/{name} by tools/make_wrist_style.py.\n"
            f"# Do not edit; edit the main style or the generator.\n\n"
            + transform(src.read_text(), name)
        )

    # The wrist variant needs its own level plan: fewer levels means smaller tiles and
    # less for the watch to draw.
    options = (SRC / "options").read_text()
    options = re.sub(
        r"^levels\s*=.*$",
        "levels = 0:24, 1:22, 2:20, 3:18",
        options,
        flags=re.M,
    )
    (DST / "options").write_text(
        "# GENERATED by tools/make_wrist_style.py\n"
        "# Fewer levels than the handlebar style: smaller tiles, less to render.\n"
        + options.replace("name=swisstopo", "name=swisstopo-wrist")
    )

    dropped = sum(
        1
        for f in ("lines", "polygons", "points")
        if (DST / f).exists()
        for line in (DST / f).read_text().splitlines()
        if line.startswith("# [wrist] dropped")
    )
    print(f"wrote {DST}")
    print(f"  {dropped} rules dropped, resolutions raised by {BUMP} (contours +{CONTOUR_BUMP})")


if __name__ == "__main__":
    main()
